### PR TITLE
Avoid .babelrc conflict with React Native

### PR DESCRIPTION
**Pull request by aksonov**
Avoid .babelrc conflict with React Native

### CODE REVIEW

**Comment by aksonov** [comment]
Corrected #4

**Comment by milankinen** [comment]
Thanks!

**Comment by milankinen** [comment]
...and [released](https://github.com/milankinen/react-reactive-toolkit/releases/tag/v0.4.1)

**Comment by aksonov** [comment]
Thanks! Published https://github.com/aksonov/react-native-reactive-counter-example, comments are welcome.

**Pull request merged**
